server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location /proxy-api/carrefour/ {
        rewrite ^/proxy-api/carrefour/(.*)$ /$1 break;
        proxy_pass https://www.carrefour.com.ar;
        proxy_set_header Host www.carrefour.com.ar;
        proxy_ssl_server_name on;
        proxy_set_header User-Agent $http_user_agent;
    }

    location /proxy-api/dia/ {
        rewrite ^/proxy-api/dia/(.*)$ /$1 break;
        proxy_pass https://diaonline.supermercadosdia.com.ar;
        proxy_set_header Host diaonline.supermercadosdia.com.ar;
        proxy_ssl_server_name on;
        proxy_set_header User-Agent $http_user_agent;
    }

    location /proxy-api/changomas/ {
        rewrite ^/proxy-api/changomas/(.*)$ /$1 break;
        proxy_pass https://www.masonline.com.ar;
        proxy_set_header Host www.masonline.com.ar;
        proxy_ssl_server_name on;
        proxy_set_header User-Agent $http_user_agent;
    }
}
