name: Automerge PR to main

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Automerge PR if all checks pass and approved
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_approve: true

