name: Automerge PR to main

on:
  push:
    branches:
      - dev

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq    
        run: sudo apt-get install -y jq

      - name: Get Pull Request number
        id: get_pr
        run: |
          PR_NUMBER=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            | jq '.[] | select(.head.ref=="dev") | .number')
          echo "pr=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Auto-merge the PR
        if: steps.get_pr.outputs.pr != ''
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.get_pr.outputs.pr }}/merge \
            -d '{"commit_title":"Auto-merge dev into main","merge_method":"merge"}'
