
name: Enable Auto-merge
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [main]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      statuses: write
      checks: write

    steps:
      - name: Enable auto-merge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.AUTOMERGE_DISPATCH }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE'
            });
            
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'merge'
            });