name: Import data into Firebase
run-name: 🔥 Import data into Firebase

on:
  schedule:
    - cron: '0 14 * * *' # Se ejecuta a las 14:00 UTC (11:00 AM ART en invierno, 10:00 AM ART en verano)
  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout 
      uses: actions/checkout@v4

    - name: Configure Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Configure Firebase Credentials (Create temporary file)
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > ./scripts/serviceAccountKey.json

    - name: Verify credentials file
      run: |
        if [ ! -f ./scripts/serviceAccountKey.json ]; then
          echo "Error: El archivo de credenciales no existe después de intentar crearlo."
          exit 1
        fi
        node -e "try { JSON.parse(require('fs').readFileSync('./scripts/serviceAccountKey.json', 'utf8')); console.log('JSON válido'); } catch(e) { console.log('JSON inválido o error de lectura:', e.message); process.exit(1); }"

    - name: Run Import Script
      run: node scripts/importProducts.js
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: './scripts/serviceAccountKey.json'

    - name: Configure Git for commit
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: Add and commit changes in the 'data' folder
      run: |
        git add src/data
        git status
        git diff --staged
        git commit -m "Update JSON data for products and branches (Automated by GH Actions)" || echo "No changes to commit"

    - name: Push changes to the main branch
      run: git push origin main

    - name: Clean up credentials
      if: always()
      run: rm -f ./scripts/serviceAccountKey.json