name: Import data into Firebase
run-name: 游댠 Import data into Firebase

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch: 

jobs:
  import-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c칩digo
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 

    - name: Instalar dependencias
      run: npm install

    - name: Configurar Credenciales de Firebase
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > ./scripts/serviceAccountKey.json

    - name: Verificar archivo de credenciales
      run: |
        if [ ! -f ./scripts/serviceAccountKey.json ]; then
          echo "Error: El archivo de credenciales no existe"
          exit 1
        fi
        node -e "try { JSON.parse(require('fs').readFileSync('./scripts/serviceAccountKey.json', 'utf8')); console.log('JSON v치lido'); } catch(e) { console.log('JSON inv치lido:', e.message); process.exit(1); }"

    - name: Configurar variables de entorno (.env para el script)
      run: |
        echo "FIREBASE_SERVICE_ACCOUNT_PATH=./scripts/serviceAccountKey.json" >> .env

    - name: Ejecutar Script de Importaci칩n
      run: node scripts/importProducts.js

    - name: Limpiar credenciales
      if: always()
      run: rm -f ./scripts/serviceAccountKey.json