name: Import data into Firebase
run-name: 游댠 Import data into Firebase

on:
  schedule:
    - cron: '0 14 * * *' # Se ejecuta a las 14:00 UTC (11:00 AM ART en invierno, 10:00 AM ART en verano)
  workflow_dispatch: 

jobs:
  import-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del c칩digo
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 

    - name: Instalar dependencias
      run: npm install

    - name: Configurar Credenciales de Firebase
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > ./scripts/serviceAccountKey.json

    - name: Verificar archivo de credenciales
      run: |
        if [ ! -f ./scripts/serviceAccountKey.json ]; then
          echo "Error: El archivo de credenciales no existe"
          exit 1
        fi
        node -e "try { JSON.parse(require('fs').readFileSync('./scripts/serviceAccountKey.json', 'utf8')); console.log('JSON v치lido'); } catch(e) { console.log('JSON inv치lido:', e.message); process.exit(1); }"

    - name: Ejecutar Script de Importaci칩n
      run: node scripts/importProducts.js

    - name: Configurar Git para el commit
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"

    - name: A침adir y commitear cambios de la carpeta 'data'
      run: |
        git add src/data
        git status # Para ver qu칠 archivos se han a침adido
        git diff --staged # Para ver los cambios antes de commitear
        git commit -m "Actualizar datos JSON de productos y sucursales (Autom치tico por GH Actions)" || echo "No hay cambios para commitear"

    - name: Push de los cambios a la rama main
      run: git push origin main

    - name: Limpiar credenciales
      if: always()
      run: rm -f ./scripts/serviceAccountKey.json