name: "Labeler PR"

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Label PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          configuration-path: .github/labeler.yml